import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from "react";
import {
  FormControl,
  InputGroup,
  ListGroup,
  Form,
  Button,
  ListGroupItem,
} from "react-bootstrap";

export default function Home() {
  const [cities, setCities] = useState([]);

  useEffect(() => {
    fetch("/api/cities")
      .then((response) => response.json())
      .then((cities) => setCities(cities));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          console.log(cities)
        }
        <ListGroup>
          {cities.map((city) => (
            <ListGroup.Item key={city.id}>
              {city.name}
            </ListGroup.Item>
          ))}
        </ListGroup>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
